In [2]:
import pandas as pd
# import matplotlib.pyplot as plt
# import numpy as np
# import seaborn as sns
# from IPython.display import Image


# Setting up max columns & rows displayed to 100
pd.options.display.max_columns = 100
pd.options.display.max_rows = 250

In [8]:
csv_path = r'C:\Users\97258\Documents\DI-Bootcamp\week_5\day_3\Daily_Challenge\IRIS.csv'

iris_db = pd.read_csv(csv_path)

iris_df = pd.DataFrame(iris_db)

nulls_only_df = iris_df[iris_df.isna().any(axis=1)]

nulls_only_df # no missing values in the df

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, species]
Index: []

In [9]:
iris_df.rename(columns={'sepal_length':'flower_protector_length',
                        'sepal_width':'flower_protector_width'
                       },inplace=True)
iris_df.head(2)

,flower_protector_length,flower_protector_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa

In [12]:
iris_df.to_excel('cleaned_iris.xlsx', index=False)

In [16]:
new_df = pd.read_excel('cleaned_iris.xlsx')

new_df = new_df.sort_values(by=['flower_protector_length'], ascending=True)
subset = new_df.iloc[0:10]
subset

,flower_protector_length,flower_protector_width,petal_length,petal_width,species
13,4.3,3.0,1.1,0.1,Iris-setosa
42,4.4,3.2,1.3,0.2,Iris-setosa
38,4.4,3.0,1.3,0.2,Iris-setosa
8,4.4,2.9,1.4,0.2,Iris-setosa
41,4.5,2.3,1.3,0.3,Iris-setosa
22,4.6,3.6,1.0,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
6,4.6,3.4,1.4,0.3,Iris-setosa
47,4.6,3.2,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa

In [19]:
subset.to_json('iris_subset.json')

pd.read_json('iris_subset.json')

,flower_protector_length,flower_protector_width,petal_length,petal_width,species
13,4.3,3.0,1.1,0.1,Iris-setosa
42,4.4,3.2,1.3,0.2,Iris-setosa
38,4.4,3.0,1.3,0.2,Iris-setosa
8,4.4,2.9,1.4,0.2,Iris-setosa
41,4.5,2.3,1.3,0.3,Iris-setosa
22,4.6,3.6,1.0,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
6,4.6,3.4,1.4,0.3,Iris-setosa
47,4.6,3.2,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa

Instructions
Data Loading: Download the Iris dataset from this link and save it as a CSV file (e.g., iris.csv). Then, load this CSV dataset into a Pandas DataFrame.

Data Cleaning - Handling Missing Values: Check for missing values in the dataset and decide how to handle them. You can either remove rows with missing values or impute them with appropriate values (e.g., using the mean or median). Document your approach and execute it.

Data Cleaning - Renaming Columns: Examine the column names in the dataset. If needed, rename the columns to make them more descriptive and meaningful. For example, you can rename columns like ‘sepal_length’ and ‘sepal_width’ for clarity.

Export to Excel: After cleaning the dataset, export it to a new Excel file (e.g., cleaned_iris.xlsx) using Pandas. Ensure that the exported file contains the cleaned data with updated column names.

Import from Excel: Import the data from the Excel file (cleaned_iris.xlsx) back into a Python DataFrame. Verify that the imported data matches the cleaned data from step 2.

Save Subset to JSON: Create a subset of the cleaned Iris dataset. For example, you can select a specific number of rows or specific columns. Export this subset to a JSON file (e.g., iris_subset.json) using Pandas.